


<!DOCTYPE html>
<html lang="ru">
<head>
    <title>jquery datatable</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.1/b-2.0.0/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4-4.6.0/jq-3.3.1/jszip-2.5.0/dt-1.11.1/af-2.3.7/b-2.0.0/b-colvis-2.0.0/b-html5-2.0.0/b-print-2.0.0/cr-1.5.4/date-1.1.1/fc-3.3.3/fh-3.1.9/kt-2.6.4/r-2.2.9/rg-1.1.3/rr-1.2.8/sc-2.0.5/sb-1.2.1/sp-1.4.0/sl-1.3.3/datatables.min.css"/>



</head>
<body>
<table id="newtable" class="table table-striped table-bordered" style="width:100%; margin: 5px">
    <thead>
    <tr>
        <th>id</th>
        <th>article</th>
        <th>title</th>
        <th>price</th>
        <th>img</th>
        <th>description</th>
    </tr>
    </thead>
    <tbody>

    <?php


    require_once "config/connect.php";
    $goods = mysqli_query($connect, "SELECT * FROM Goods");

    $goods = mysqli_fetch_all($goods);
    foreach ($goods as $good) {
        ?>
        <tr>
            <td><?= $good[0] ?></td>
            <td><?= $good[1] ?></td>
            <td><?= $good[2] ?></td>
            <td><?= $good[3] ?></td>
            <td><?= $good[4] ?></td>
            <td><?= $good[5] ?></td>

        </tr>
        <?php
    }


    ?>

    </tbody>


</table>


<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">



<div class="modal fade" id="add_data">
    <form action="crud/create.php" method="POST">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Добавить данные</h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                    <p>Артикул</p>
                    <input type="text" name="article" id="article">
                    <p>Название</p>
                    <input type="text" name="title" id="title">
                    <p>Цена</p>
                    <input type="number" name="price" id="price">
                    <p>Картинка</p>
                    <input type="file" name="img" id="img">
                    <p>Описание</p>
                    <input type="text" name="description" id="description">



                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="submit" name="insertdata" class="btn btn-primary">Добавить</button>
                </div>
            </div>
        </div>
    </form>
</div>




<div class="modal fade" id="updateWindow">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" >Редактировать данные</h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form action="crud/update.php" method="POST">
                <div class="modal-body">


                    <input type = "hidden" name = "update_id" id = "update_id">
                    <p>Артикул</p>
                    <input type="text" name="article1" id="article1">
                    <p>Название</p>
                    <input type="number" name="title1" id="title1">
                    <p>Цена</p>
                    <input type="number" name="price1" id="price1">
                    <p>Картинка</p>
                    <input type="file"   accept="image/*" onchange="loadFile1(event)">
                    <img id="img1" style = "width:100%; height: auto;"/>
                    <input type = "hidden" name = "img_url1" id = "img_url1">
                    <script>
                        var loadFile1 = function(event) {
                            var output = document.getElementById('img1');
                            output.src = URL.createObjectURL(event.target.files[0]);
                            $('#img_url1').val(output.src);
                        };
                    </script>
                    <p>Описание</p>
                    <input type="text" name="description1" id="description1">



                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="submit" name="updatedata" class="btn btn-success">Редактировать</button>

                </div>
            </form>
        </div>
    </div>

</div>








<div class="modal fade" id="deleteWindow">

    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>


                <div class="modal-body">
                    <input type = "hidden" name = "delete_id" id = "delete_id">
                    <p>Вы действительно желаете удалить товар?</p>



                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>

                    <button name="delete" id ='delete' class="btn btn-danger">Да</button>

                </div>


        </div>
    </div>

</div>






</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4-4.6.0/jq-3.3.1/jszip-2.5.0/dt-1.11.1/af-2.3.7/b-2.0.0/b-colvis-2.0.0/b-html5-2.0.0/b-print-2.0.0/cr-1.5.4/date-1.1.1/fc-3.3.3/fh-3.1.9/kt-2.6.4/r-2.2.9/rg-1.1.3/rr-1.2.8/sc-2.0.5/sb-1.2.1/sp-1.4.0/sl-1.3.3/datatables.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>



<script>
    $(document).ready(function () {
        var table = $('#newtable').DataTable( {
            dom: 'Bfrtip',
            select: {
                style: 'multi'
            },
            buttons: [{
                text: "Добавить",
                action: function (){
                    $('#article').val('');
                    $('#price').val('');
                    $('#title').val('');
                    $('#img').val('');
                    $('#description').val('');
                    $('#add_data').modal().fadeIn();


                }},

                {
                    text: "Редактировать",
                    action: function (){
                        var data = table.rows({selected:true}).data()['0'];
                        $('#update_id').val(data[0]);
                        $('#article1').val(data[1]);
                        $('#title1').val(data[2]);
                        $('#price1').val(data[3]);
                        $('#img1').val('');
                        $('#description1').val(data[5]);
                        $('#updateWindow').modal().fadeIn();

                    },
                    init:function (dt,node,config){
                        var that = this;
                        dt.on('select.dt.DT deselect.dt.DT', function (){
                            that.enable(dt.rows({
                                selected:true
                            }).count()===1);
                        });
                        that.disable();
                    }

                },

                {
                    text: "Удалить",
                    action: function (){
                        var data = table.rows({selected:true}).data()['0'];
                        $('#deleteWindow').modal().fadeIn();
                        //для удаления одной строки
                        // $('#delete_id').val(data[0]);


                    },
                    init:function (dt,node,config){
                        var that = this;
                        dt.on('select.dt.DT deselect.dt.DT', function (){
                            that.enable(dt.rows({
                                selected:true
                            }).count()>=1);
                        });
                        that.disable();
                    }
                },
            ]
        });
        $("#delete").click(function(){
            var data1 = table.rows({selected:true}).data();
            console.log(data1);
            var array = [];
            for (var i=0; i<=data1['length']-1; i++) {

                array.push(data1[i][0]);

            }
            $.ajax({
                type: "POST",
                url: "crud/delete.php",
                data:{ array:array},
                success: function(data1) {

                        window.location.replace("/index.phtml");
                    },

                }
            );

        });

    });




</script>



</html>




